name: 'Close stale PR and Issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-message: 'This PR is stale because it has been open 24 months with no activity. Remove stale label or comment or this will be closed in 30 days.'
          days-before-pr-stale: 730
          days-before-pr-close: 30
